
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    binary: kcc
    main: ./main
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    hooks:
      post:
        - go mod tidy
        - go test -v ./...
      pre:
        - go generate ./...
        - go vet ./...
