name: Release
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
    - name: Setup Snapcraft
      run: |
        # https://github.com/goreleaser/goreleaser/issues/1715
        mkdir -p $HOME/.cache/snapcraft/download
        mkdir -p $HOME/.cache/snapcraft/stage-packages
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
